---
title: "Untitled"
author: '520345357'
date: "2026-03-06"
output: html_document
---

```{r setup, include=FALSE}
# Load in datasets and libraries
library(GEOquery)
library(glmnet)
library(pROC)
library(caret)
library(Biobase)
library(ggplot2)
library(limma)
library(Hmisc)
gse_internal <- readRDS("C:/Users/12250/Desktop/171225/MPhil/eplet/GSE147089.rds")
gse_external <- readRDS("C:/Users/12250/Desktop/171225/MPhil/eplet/GSE129166.rds")
```

```{r}
# Data preprocessing-------------------------------------------------------------

# Expression and phenotype
exprset_internal <- gse_internal[[1]]
exprset_external <- gse_external[[1]]
expr_internal <- exprs(exprset_internal)
pheno_internal <- pData(exprset_internal)
expr_external <- exprs(exprset_external)
pheno_external <- pData(exprset_external)

# Look at dimensions = external has more probes, so need to align both datasets
dim(expr_internal)
dim(expr_external)

# Outcome columns in the two datasets
unique(pheno_internal$`phenotype:ch1`)
unique(pheno_external$characteristics_ch1.2)
```


```{r}
# Data preprocessing-------------------------------------------------------------

# Make sure to use the same genes
common_genes <- intersect(rownames(expr_internal), rownames(expr_external))
expr_internal <- expr_internal[common_genes, ]
expr_external <- expr_external[common_genes, ]

# Check relevant column in internal dataset
label_internal_raw <- pheno_internal$characteristics_ch1
y_internal <- ifelse(grepl("No ABMRh", label_internal_raw), 0, 1)
y_external <- as.numeric(gsub(".*: ", "", pheno_external$characteristics_ch1.2))

# Outcomes in the two datasets
table(y_internal)
table(y_external)
x_int1 <- t(as.matrix(expr_internal))
x_ext1 <- t(as.matrix(expr_external))

x_int <- scale(x_int1)  

# Apply same scaling to external dataset
# Note: use the training mean and sd
mean_train <- attr(x_int, "scaled:center")
sd_train   <- attr(x_int, "scaled:scale")
x_ext <- scale(x_ext1, center = mean_train, scale = sd_train)

cat("Internal and external expression dimension:\n")
dim(x_int)
dim(x_ext)

```


```{r}
# Train/test split---------------------------------------------------------------

# Train/test split for internal (70%/30%)
set.seed(20)

split_func<-function(x_int, y_internal){
train_index <- createDataPartition(y_internal, p = 0.75, list = FALSE)

# Training data
x_train <- x_int[train_index, , drop = FALSE]
y_train <- y_internal[train_index]

# Testing data
x_test  <- x_int[-train_index, , drop = FALSE]
y_test  <- y_internal[-train_index]

# Formatting
y_train_num <- as.numeric(y_train)
x_train_mat <- as.matrix(x_train)

y_test_num <- as.numeric(y_test)
x_test_mat <- as.matrix(x_test)

return(list(
  x = x_train_mat,
  y = y_train_num,
  a = x_test_mat,
  b = y_test_num
))
}

train_test<-split_func(x_int, y_internal)
x_train_mat<-train_test$x
y_train_num<-train_test$y
```




```{r}
# cv 10 fold---------------------------------------------------------------------

set.seed(13)   # for reproducibility

cv_func <- function(x_train_mat, y_train_num) {
  
  n_iter <- 20
  auc_values2 <- vector("list", n_iter)   # store AUC vectors
  
  for (i in 1:n_iter) {
    
    y_factor <- as.factor(y_train_num)
    folds <- createFolds(y_factor, k = 3, list = TRUE, returnTrain = FALSE)
    
    auc_k <- numeric(3)   # AUC for each of the 3 folds
    
    for (k in 1:3) {
      test_idx  <- folds[[k]]
      train_idx <- setdiff(seq_along(y_train_num), test_idx)
      
      x_train <- x_train_mat[train_idx, ]
      y_train <- y_train_num[train_idx]
      
      x_test  <- x_train_mat[test_idx, ]
      y_test  <- y_train_num[test_idx]
      
      # DE genes (hyper-parameter tuning: feature selection)
      y_train_num1 = as.factor(y_train)
      
      design <- model.matrix(~ y_train_num1)
      
      fit <- lmFit(t(x_train), design)
      
      fit <- eBayes(fit)
      
      deg_500 <- topTable(fit, coef = 2, number = 500)
      
      genes_500 <- rownames(deg_500)
      
      x_train <- x_train[,genes_500]
      x_test<- x_test[,genes_500]

      
      fit <- glmnet(
        x_train, y_train,
        family = "binomial",
        alpha  = 1,
        lambda = 0.1
      )
      
      prob_k <- as.numeric(predict(fit, newx = x_test, type = "response"))
      
      auc_k[k] <- suppressMessages(auc(y_test, prob_k))
    }
    
    auc_values2[[i]] <- auc_k
  }
  
  return(unlist(auc_values2))   # 20 × 3 = 60 AUC values
}

cv_result1<-cv_func(x_train_mat,y_train_num)

```


```{r}
# CV dataset for plotting
box_df_cv1 <- data.frame(
  category = "CV",
  auc = cv_result1
)
```


```{r}
# Internal validation------------------------------------------------------------

internal_func<-function(x_train_mat,y_train_num,x_test_mat, y_test_num){
  
  y_train_num1 = as.factor(y_train_num)

design <- model.matrix(~ y_train_num1)

fit <- lmFit(t(x_train_mat), design)

fit <- eBayes(fit)

deg_500 <- topTable(fit, coef = 2, number = 500)

genes_500 <- rownames(deg_500)

x_train_mat <- x_train_mat[,genes_500]
x_test_mat <- x_test_mat[,genes_500]


  fit1 <- glmnet(
    x_train_mat,
    y_train_num,
    family = "binomial",
    alpha  = 1,
    lambda = 0.1
  )
  
  # Predictions (probabilities)
  pred_prob <- as.numeric(
    predict(fit1, newx = x_test_mat, type = "response")
  )
  
  # AUC
  auc_value <- suppressMessages(auc(y_test_num, pred_prob))
  return(auc_value)}


int1<-internal_func(train_test$x,train_test$y,train_test$a,train_test$b)

# External validation------------------------------------------------------------
ext1<-internal_func(x_int,y_internal,x_ext,y_external)
```

```{r}
# Internal and external datasets for plotting
box_df_cv11 <- data.frame(
  category = c("Internal hold-out", "External"),
  auc = c(int1, ext1) 
)
```


```{r}
# Combine datasets for plotting
final_df<-rbind(box_df_cv1,box_df_cv11)

# Boxplot
 # Ensure Hmisc is loaded for mean_cl_normal

myplot<-ggplot(final_df, aes(x = category, y = auc)) +
  # 1. Raw data dots
  geom_jitter(data = box_df_cv1, aes(x = category, y = auc), 
              width = 0.2, alpha = 0.4, color = "lightblue") +
  # 2. Mean point
  stat_summary(data = box_df_cv1, aes(x = category, y = auc), 
               fun = mean, geom = "point", color = "steelblue", size = 3) +
  # 3. CI error bars
  stat_summary(data = box_df_cv1, aes(x = category, y = auc), 
               fun.data = mean_cl_normal, geom = "errorbar", 
               width = 0.2, color = "steelblue") +
  # Keep original elements
  geom_point(data = box_df_cv11, aes(x = category, y = auc),
             color = "hotpink", size = 3) +
  scale_y_continuous(limits = c(0.5, 0.99)) +
  scale_x_discrete(limits = c("CV", "Internal hold-out", "External")) +
  theme_minimal() +
  labs(
    x = "Validation type",
    y = "AUC",
    title = "AUC distribution: Cross-validation (CV) vs internal hold-out vs external"
  )

ggsave(
  filename = "C:/Users/12250/Desktop/171225/MPhil/eplet/auc_distribution_plot.pdf", 
  plot = myplot,
  width = 7,       # Width in inches
  height = 5,      # Height in inches
  device = "pdf"
)

# Results from 3 validation strategies
mean(cv_result1)
int1
ext1
```


